### ISSUE TITLE
Debian packager request: Please tag your releases

### ISSUE THREAD

**Issue by dod38fr** [raku-community-modules/File-Find#39]
Hello

In Debian, we have a toolset (i.e. [uscan](https://manpages.debian.org/unstable/devscripts/uscan.1.en.html)) to track upstream release that work on GitHub tags.

Without release tags, the tracking tools are not working and we are not aware when a new release is mage. Which means Debian packages will lag behind your releases.

So please tag at least the last release and any future release.

All the best

Dod (for Debian)

**Comment by tbrowder** [comment]
My PR to be submitted soon incorporates App::Mi6 management. Hopefully that will take care of this issue.

**Comment by lizmat** [comment]
tbrowder: I think I already did that?

**Comment by tbrowder** [comment]
Yes, I see that now. Thanks.

**Comment by lizmat** [comment]
I don't plan doing any of that  :-)
