### ISSUE TITLE
Please "git tag" your RAKU modules versions

### ISSUE THREAD

**Issue by AntonOks** [raku-community-modules/File-Find#40]
can you please "GIT TAG" your RAKU modules with it's version, similar and at the same time you maintain it's **_"version": "x.y.z"_** in your `META6.json` file?

this is highly appreciated in regards to "reproducible builds" and especially for the ["Rakudo Star" modules](https://github.com/rakudo/star/blob/master/etc/modules.txt)

THANK YOU!

**Comment by lizmat** [comment]
I think this is now done.  Please re-open if you disagree.
