### ISSUE TITLE
Parameter :keep-going is broken

### ISSUE THREAD

**Issue by tbrowder** [raku-community-modules/File-Find#41]

**Comment by 2colours** [comment]
What do you mean by "broken"? I'm using it and it seems okay...

**Comment by tbrowder** [comment]
I failed to read the docs. I confused :keep-going with the hard-to-see :recursive.

**Comment by 2colours** [comment]
Can this issue be closed, then?

**Comment by tbrowder** [comment]
Yes, but please consider my PR.
